-- vim.pack.add({ { src = 'https://github.com/nvim-treesitter/nvim-treesitter', branch = 'master' } })
--
-- require('nvim-treesitter.configs').setup({
--   ensure_installed = {
--     'bash',
--     'c',
--     'diff',
--     'html',
--     'lua',
--     'luadoc',
--     'markdown',
--     'markdown_inline',
--     'query',
--     'vim',
--     'vimdoc',
--     'javascript',
--     'typescript',
--     'tsx',
--   },
--   auto_install = true,
--   highlight = {
--     enable = true,
--     additional_vim_regex_highlighting = { 'ruby' },
--   },
--   conceal = { enable = false },
--   indent = { enable = true, disable = { 'ruby' } },
-- })
